### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by lomonosov77** [itelmenko/docker-grandpa-php#1]
Hello! 
Step 5/13
ERROR: Service 'main' failed to build: The command '/bin/sh -c locale-gen fr_FR.UTF-8     locale-gen tr_TR.UTF-8     locale-gen de_DE.UTF-8     locale-gen ja_JP.UTF-8     locale-gen ru_RU.UTF-8     locale-gen en_US.UTF-8     locale-gen es_ES.UTF-8     locale-gen it_IT.UTF-8     locale-gen pl_PL.UTF-8     locale-gen pt_BR.UTF-8     locale-gen pt_PT.UTF-8 COPY apache_default /etc/apache2/sites-available/default' returned a non-zero code: 1
Do you know how to resolv it?

**Comment by itelmenko** [comment]
Hi! Thanks for bug report. I have fixed it.
You can update local copy of repository and rebuild 

```
docker-compose build main mariadb
```

Then use
```
docker-compose up -d main mariadb  
```
